version: 2
jobs:
  build:
    parallelism: 2
    docker:
      - image: circleci/python:3.7.0

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "setup.py" }}
            - v1-dependencies-{{ .Branch }}
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            mkdir ~/tasks_db/
            touch ~/tasks_db/tasks_db.json
            pip install .
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ .Branch }}-{{ checksum "setup.py" }}
      - run:
          name: run tests
          command: |
            . venv/bin/activate
       #     pytest --junitxml=test-reports/junit.xml $(circleci tests glob tests/**/test_*.py | circleci tests split)
             pytest -vvl
      - store_test_results:
          path: test-reports
